import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const versionFile = resolve(__dirname, "../src/version.ts");
const pkg = JSON.parse(readFileSync(resolve(__dirname, "../package.json"), "utf-8"));

const repoRoot = resolve(__dirname, "../..");
let commitHash = "unknown";
try {
  commitHash = execSync("git rev-parse --short HEAD", { cwd: repoRoot }).toString().trim();
} catch {
  /* not a git checkout or git unavailable */
}

const version = `${pkg.version}+${commitHash}`;

writeFileSync(
  versionFile,
  `// Auto-generated by scripts/version.js — do not edit manually.\nexport const APP_VERSION = "${version}";\n`
);
