import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const manifestFile = resolve(__dirname, "../src/runtimeManifest.ts");
const pkg = JSON.parse(readFileSync(resolve(__dirname, "../package.json"), "utf-8"));
const repoRoot = resolve(__dirname, "../..");

let commitHash = "unknown";
let dirtySuffix = "";
try {
  commitHash = execSync("git rev-parse --short HEAD", { cwd: repoRoot }).toString().trim();
  const dirtyOutput = execSync("git status --porcelain", { cwd: repoRoot })
    .toString()
    .split("\n")
    .filter(
      (line) =>
        !line.endsWith("client/src/version.ts") &&
        !line.endsWith("server/src/runtimeManifest.ts")
    )
    .join("\n")
    .trim();
  if (dirtyOutput) {
    const dirtyHash = dirtyOutput
      .split("")
      .reduce((hash, char) => ((hash << 5) - hash + char.charCodeAt(0)) | 0, 0);
    dirtySuffix = `.dirty.${Math.abs(dirtyHash).toString(16).padStart(8, "0")}`;
  }
} catch {
  /* not a git checkout or git unavailable */
}

const buildId = process.env.BUILD_ID || `${pkg.version}+${commitHash}${dirtySuffix}`;
writeFileSync(
  manifestFile,
  `// Auto-generated by server/scripts/version.js — do not edit manually.\nexport const RUNTIME_MANIFEST = { syncProtocol: 2, buildId: "${buildId}" } as const;\n`
);
